from openpyxl.styles import colors
from openpyxl.styles import Alignment, Border, Color, Font, PatternFill, Protection, Side
from openpyxl.utils import get_column_letter, column_index_from_string


COLOR_WHITE='00FFFFFF'
COLOR_LIGHTBLACK='00282828'
COLOR_DARKGREY='00505050'
COLOR_DARKRED='00600000'

ALIGNMENT = Alignment(
    wrap_text=True, horizontal="center", vertical="center"
)

class Style:


  def generate_header(self, row: int, col: int, currentSheet: object, heading: str = 'Header', value: str = 'Item') -> object:
              # Add horizontal header
              # [ Day 1 ]
              currentSheet.merge_cells(
                  start_row=row, end_row=row,
                  start_column=col, end_column=col+COLUMN_LENGTH
              )

              currentCell = currentSheet.cell(
                  row=row, column=col, value=f"{heading} {value}"
              )

              return currentCell


  def generate_block(self, row: int, col: int, currentSheet: object, value: str = 'Item') -> object:
              # Add a single cell header
              # [ Block ]

              currentCell = currentSheet.cell(
                  row=row, column=col, value=f"{value}"
              )

              self.set_style(
                  currentSheet, currentCell, col,
                  fgColor=colors.WHITE, bgColor=COLOR_DARKRED,
                  size=18, width=20, font='Helvetica', bold=True
              )

              currentCell.alignment = ALIGNMENT

              return currentCell


  def generate_sheet_banner(self, currentSheet: object, value: str = 'Item') -> None:
              # Get last column of spreadsheet for full banner
              max_col = currentSheet.max_column

              # Print week banner on first row
              currentSheet.merge_cells(
                  start_row=1, end_row=1,
                  # Calculate total columns in sheet
                  start_column=1, end_column=max_col
              )
              currentCell = currentSheet.cell(
                  row=1, column=1, value=f"{value}"
              )
              self.set_style(
                  currentSheet, currentCell, 1,
                  fgColor=colors.WHITE, bgColor=COLOR_DARKRED,
                  size=28, width=10, font='Helvetica', bold=True
              )
              currentCell.alignment = ALIGNMENT

              # Print date banner on second row
              date = datetime.datetime.now().strftime("%m/%d/%Y")
              currentSheet.merge_cells(
                  start_row=2, end_row=2,
                  # Calculate total columns in sheet
                  start_column=1, end_column=max_col
              )
              currentCell = currentSheet.cell(
                  row=2, column=1, value=f"Generated by Time to Train on {date}"
              )
              currentCell.hyperlink = "https://github.com/jonschipp/timetotrain"
              currentCell.style = "Hyperlink"
              self.set_style(
                  currentSheet, currentCell, 1,
                  fgColor=colors.WHITE, bgColor=COLOR_LIGHTBLACK,
                  size=12, width=10, font='Helvetica', bold=False
              )
              currentCell.alignment = ALIGNMENT


  def generate_divide(self, row: int, col: int, currentSheet: object, heading: str = 'Header', style: str = 'manual') -> object:
              # Create divide with header and input
              # [         ][         ]
              # [ Program ][ <input> ]
              # [         ][         ]
              color = COLOR_DARKGREY
              bold = False

              if style == 'formula':
                  color = COLOR_DARKRED
                  bold = True

              currentCell = currentSheet.cell(
                  row=row, column=col, value=f"{heading}"
              )

              currentSheet.merge_cells(
                  start_row=row, end_row=row, start_column=col+1, end_column=col+COLUMN_LENGTH
              )

              self.set_style(
                  currentSheet, currentCell, col,
                  fgColor=colors.WHITE, bgColor=color,
                  size=12, width=20, font='Helvetica', bold=bold
              )

              currentCell = currentSheet.cell(
                  row=row, column=col+1
              )

              if style == 'formula':
                  self.set_style(
                      currentSheet, currentCell, col,
                      fgColor=colors.WHITE, bgColor=color,
                      size=12, width=20, font='Helvetica', bold=False
                  )

              currentCell.alignment = ALIGNMENT

              return currentCell


  def set_formula(self, currentCell: object, formula: str) -> None:
        currentCell.value = formula
        currentCell.alignment = ALIGNMENT



  def set_style(self, sheet: object, cell: object, col: int, fgColor: str, bgColor: str, size: int, width: int, font: str, bold: bool = False) -> object:
        # Set style
        font = Font(
            name=font, size=size, bold=bold, color=fgColor
        )
        fill = PatternFill(
            fill_type='solid', fgColor=bgColor,
        )

        sheet.column_dimensions[get_column_letter(col)].width = width
        cell.font = font
        cell.fill = fill
        cell.alignment = ALIGNMENT
        return cell


  def clear(self) -> None:
     # Make remaining of our cells white and borderless
     #white = PatternFill(fill_type='solid', fgColor=colors.WHITE)
     color = PatternFill(fill_type='solid', fgColor=COLOR_LIGHTBLACK)
     for sheet in self.wb.worksheets:
         for row in sheet:
             for currentCell in row:
                 if currentCell.alignment.horizontal == 'center':
                     # Skip the cells we created
                     continue
                 currentCell.fill = color
